---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: qlik/gradle
    tag: latest

inputs:
- name: easy-api-gateway
- name: apigateway-version

outputs:
- name: builds

run:
  path: easy-api-gateway/ci/build.sh